# Learning Python - 5
## NumPy and Complex Arrays

NumPy library for python is a part of SciPy libraries or scientific python libraries. Numpy deals with complex arrays of N dimensions and also matrix mathematics, differentiation, integrations etc.

We import `numpy` as a package like this.
```python
import numpy as np
```

In [1]:
import numpy as np

It gives us an np object to work with. the `np` object can be used for many things. First, let's define an array with 10 elements.

In [2]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


Now, let's convert this array into a multi dimensional array.
We do that by using
```python
np.array(a).reshape(row, col)
```

In [3]:
arr = np.array(arr).reshape(2,5)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In case you're wondering, we can reshape it again.

In [5]:
arr = arr.reshape(5,2)
print(arr)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Enough fun, let's change the second column to something random. We use the `randint()` function for that.

In [7]:
from random import randint

In [12]:
x, y = arr.shape

In [13]:
for i in range(x):
    arr[i, 1] = randint(1, 100)
    
print(arr)

[[ 0 29]
 [ 2 18]
 [ 4 40]
 [ 6 69]
 [ 8 50]]


To revise what we just did there,
```python
x, y = arr.shape
```
This line stored the number of rows in `x` and number of columns in `y`
Then we ran a `for` loop from 0 to `x` using `range(x)`.
```python
arr[i, 1] = randint(1,100)
```
`arr[i, 1]` means i-th row and 1st column of the matrix, and we are assigning a random integer between 1, 100.